train:
  debug: False
  batch_size: 1
  model_dir: models/
  checkpoint_file:
  ignore_scope:
  log_dir: /tmp/luminoth/
  save_every: 1000
  tf_debug: False
  run_name:
  no_log: False
  display_every: 1
  random_shuffle: True
  save_timeline: False
  summary_every: 1
  full_trace: False
  initial_learning_rate: 0.0001
  learning_rate_decay: 400000
  learning_rate_decay_method: piecewise_constant
  optimizer_type: momentum
  momentum: 0.9
  num_epochs: 10000

dataset:
  dir: 'datasets/voc/tf'
  subset: train
  image_preprocessing:
    min_size: 600
    max_size: 1024
  data_augmentation:
    flip_y: True

network:
  num_classes: 20
  with_rcnn: True
  pretrained_net: vgg_16
  pretrained_trainable: False
  pretrained_weights:

loss:
  rpn_cls_loss_weight: 1.0
  rpn_reg_loss_weights: 2.0
  rcnn_cls_loss_weight: 1.0
  rcnn_reg_loss_weights: 2.0

anchors:
  base_size: 256
  scales: [0.5, 1, 2]
  ratios: [0.5, 1, 2]
  stride: 16

rpn:
  num_channels: 512
  kernel_shape: [3, 3]
  initializer:
    type: truncated_normal_initializer
    mean: 0.0
    stddev: 0.01
  l2_regulalization_scale: 0.0005  # disable using 0
  activation_function: relu6

  proposals:
    pre_nms_top_n: 12000
    post_nms_top_n: 20000
    nms_threshold: 0.6
    min_size: 0  # disable using 0

  target:
    allowed_border: 0
    clobber_positives: False
    foreground_threshold: 0.7
    background_threshold_high: 0.3
    background_threshold_low: 0.
    foreground_fraction: 0.5
    minibatch_size: 256
    random_seed:  # only to be used for debugging

rcnn:
  enabled: True  # if disabled, then the rest of the config values will not be used.
  layer_sizes: [4096, 4096]
  dropout_keep_prop: 1.0
  activation_function: relu6
  initializer:
    type: variance_scaling_initializer
    factor: 1.0
    uniform: True
    mode: FAN_AVG
  l2_regulalization_scale: 0.0005

  roi:
    pooling_mode: CROP
    pooled_with: 7
    pooled_height: 7
    padding: VALID

  proposals:
    class_max_detections: 100
    class_nms_threshold: 0.6
    total_max_detections: 300

  target:
    foreground_fraction: 0.25
    minibatch_size: 64
    foreground_threshold: 0.5
    background_threshold_high: 0.5
    background_threshold_low: 0.1
